## A short description of numpy array ordering

Motivation: It was found that hera_gpu is returning incorrect values. This was due to the numpy `antpos` array being stored in FORTRAN order in memory. The `antpos` array is produced by this line in hera_sim:
```
self.antpos = self.uvdata.get_ENU_antpos()[0].astype(self._real_dtype)
```
It is not known why `antpos` is produced in FORTRAN order.

‘’FORTRAN order’’ refers to the internal representation of the numpy array. This is different to how the array appears to Python. Printing a numpy array gives the same result regardless of the internal representation. That is demonstrated here.

### Create a numpy array

Print the information about the ordering (CONTIGUOUS flags).

In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")
print(a.flags)

[[1 2 3]
 [4 5 6]] 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



The array is in C order (C_CONTIGUOUS = True)

### Change the array to FORTRAN order

In [5]:
a = np.asfortranarray(a)
print(a.flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



The array is in FORTRAN order (F_CONTIGUOUS = True)

### Print the array

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


Even though the array is in FORTRAN order, it prints the same. The internal representation doesn't effect how Python uses the array. However, it does effect how the GPU uses the array. The GPU array will be in FORTRAN order inside the GPU.